package br.com.ernanilima.jmercadobackend.domain.addressBr;

import lombok.AllArgsConstructor;
import lombok.Getter;

import static br.com.ernanilima.jmercadobackend.domain.addressBr.Country.BRASIL;
import static br.com.ernanilima.jmercadobackend.domain.addressBr.CountryRegion.*;
import static br.com.ernanilima.jmercadobackend.domain.addressBr.State.*;

public class City {

    @Getter
    @AllArgsConstructor
    public enum RONDONIA {
        ALTA_FLORESTA_DOESTE("ALTA FLORESTA D'OESTE", "1100015", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        ALTO_ALEGRE_DOS_PARECIS("ALTO ALEGRE DOS PARECIS", "1100379", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        ALTO_PARAISO("ALTO PARAISO", "1100403", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        ALVORADA_DOESTE("ALVORADA D'OESTE", "1100346", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        ARIQUEMES("ARIQUEMES", "1100023", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        BURITIS("BURITIS", "1100452", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        CABIXI("CABIXI", "1100031", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        CACAULANDIA("CACAULANDIA", "1100601", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        CACOAL("CACOAL", "1100049", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        CAMPO_NOVO_DE_RONDONIA("CAMPO NOVO DE RONDONIA", "1100700", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        CANDEIAS_DO_JAMARI("CANDEIAS DO JAMARI", "1100809", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        CASTANHEIRAS("CASTANHEIRAS", "1100908", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        CEREJEIRAS("CEREJEIRAS", "1100056", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        CHUPINGUAIA("CHUPINGUAIA", "1100924", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        COLORADO_DO_OESTE("COLORADO DO OESTE", "1100064", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        CORUMBIARA("CORUMBIARA", "1100072", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        COSTA_MARQUES("COSTA MARQUES", "1100080", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        CUJUBIM("CUJUBIM", "1100940", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        ESPIGAO_DOESTE("ESPIGAO D'OESTE", "1100098", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        GOVERNADOR_JORGE_TEIXEIRA("GOVERNADOR JORGE TEIXEIRA", "1101005", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        GUAJARAMIRIM("GUAJARA-MIRIM", "1100106", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        ITAPUA_DO_OESTE("ITAPUA DO OESTE", "1101104", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        JARU("JARU", "1100114", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        JIPARANA("JI-PARANA", "1100122", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        MACHADINHO_DOESTE("MACHADINHO D'OESTE", "1100130", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        MINISTRO_ANDREAZZA("MINISTRO ANDREAZZA", "1101203", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        MIRANTE_DA_SERRA("MIRANTE DA SERRA", "1101302", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        MONTE_NEGRO("MONTE NEGRO", "1101401", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        NOVA_BRASILANDIA_DOESTE("NOVA BRASILANDIA D'OESTE", "1100148", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        NOVA_MAMORE("NOVA MAMORE", "1100338", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        NOVA_UNIAO("NOVA UNIAO", "1101435", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        NOVO_HORIZONTE_DO_OESTE("NOVO HORIZONTE DO OESTE", "1100502", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        OURO_PRETO_DO_OESTE("OURO PRETO DO OESTE", "1100155", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        PARECIS("PARECIS", "1101450", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        PIMENTA_BUENO("PIMENTA BUENO", "1100189", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        PIMENTEIRAS_DO_OESTE("PIMENTEIRAS DO OESTE", "1101468", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        PORTO_VELHO("PORTO VELHO", "1100205", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        PRESIDENTE_MEDICI("PRESIDENTE MEDICI", "1100254", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        PRIMAVERA_DE_RONDONIA("PRIMAVERA DE RONDONIA", "1101476", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        RIO_CRESPO("RIO CRESPO", "1100262", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        ROLIM_DE_MOURA("ROLIM DE MOURA", "1100288", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        SANTA_LUZIA_DOESTE("SANTA LUZIA D'OESTE", "1100296", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        SERINGUEIRAS("SERINGUEIRAS", "1101500", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        SAO_FELIPE_DOESTE("SAO FELIPE D'OESTE", "1101484", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        SAO_FRANCISCO_DO_GUAPORE("SAO FRANCISCO DO GUAPORE", "1101492", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        SAO_MIGUEL_DO_GUAPORE("SAO MIGUEL DO GUAPORE", "1100320", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        TEIXEIROPOLIS("TEIXEIROPOLIS", "1101559", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        THEOBROMA("THEOBROMA", "1101609", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        URUPA("URUPA", "1101708", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        VALE_DO_ANARI("VALE DO ANARI", "1101757", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        VALE_DO_PARAISO("VALE DO PARAISO", "1101807", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name()),
        VILHENA("VILHENA", "1100304", BRASIL.getCode(), RONDONIA.getCode(), NORTE.name());

        private String description;
        private String code;
        private String country;
        private String state;
        private String region;
    }

    @Getter
    @AllArgsConstructor
    public enum ACRE {
        ACRELANDIA("ACRELANDIA", "1200013", BRASIL.getCode(), ACRE.getCode(), NORTE.name()),
        ASSIS_BRASIL("ASSIS BRASIL", "1200054", BRASIL.getCode(), ACRE.getCode(), NORTE.name()),
        BRASILEIA("BRASILEIA", "1200104", BRASIL.getCode(), ACRE.getCode(), NORTE.name()),
        BUJARI("BUJARI", "1200138", BRASIL.getCode(), ACRE.getCode(), NORTE.name()),
        CAPIXABA("CAPIXABA", "1200179", BRASIL.getCode(), ACRE.getCode(), NORTE.name()),
        CRUZEIRO_DO_SUL("CRUZEIRO DO SUL", "1200203", BRASIL.getCode(), ACRE.getCode(), NORTE.name()),
        EPITACIOLANDIA("EPITACIOLANDIA", "1200252", BRASIL.getCode(), ACRE.getCode(), NORTE.name()),
        FEIJO("FEIJO", "1200302", BRASIL.getCode(), ACRE.getCode(), NORTE.name()),
        JORDAO("JORDAO", "1200328", BRASIL.getCode(), ACRE.getCode(), NORTE.name()),
        MANOEL_URBANO("MANOEL URBANO", "1200344", BRASIL.getCode(), ACRE.getCode(), NORTE.name()),
        MARECHAL_THAUMATURGO("MARECHAL THAUMATURGO", "1200351", BRASIL.getCode(), ACRE.getCode(), NORTE.name()),
        MANCIO_LIMA("MANCIO LIMA", "1200336", BRASIL.getCode(), ACRE.getCode(), NORTE.name()),
        PLACIDO_DE_CASTRO("PLACIDO DE CASTRO", "1200385", BRASIL.getCode(), ACRE.getCode(), NORTE.name()),
        PORTO_ACRE("PORTO ACRE", "1200807", BRASIL.getCode(), ACRE.getCode(), NORTE.name()),
        PORTO_WALTER("PORTO WALTER", "1200393", BRASIL.getCode(), ACRE.getCode(), NORTE.name()),
        RIO_BRANCO("RIO BRANCO", "1200401", BRASIL.getCode(), ACRE.getCode(), NORTE.name()),
        RODRIGUES_ALVES("RODRIGUES ALVES", "1200427", BRASIL.getCode(), ACRE.getCode(), NORTE.name()),
        SANTA_ROSA_DO_PURUS("SANTA ROSA DO PURUS", "1200435", BRASIL.getCode(), ACRE.getCode(), NORTE.name()),
        SENA_MADUREIRA("SENA MADUREIRA", "1200500", BRASIL.getCode(), ACRE.getCode(), NORTE.name()),
        SENADOR_GUIOMARD("SENADOR GUIOMARD", "1200450", BRASIL.getCode(), ACRE.getCode(), NORTE.name()),
        TARAUACA("TARAUACA", "1200609", BRASIL.getCode(), ACRE.getCode(), NORTE.name()),
        XAPURI("XAPURI", "1200708", BRASIL.getCode(), ACRE.getCode(), NORTE.name());

        private String description;
        private String code;
        private String country;
        private String state;
        private String region;
    }

    @Getter
    @AllArgsConstructor
    public enum AMAZONAS {
        ALVARAES("ALVARAES", "1300029", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        AMATURA("AMATURA", "1300060", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        ANAMA("ANAMA", "1300086", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        ANORI("ANORI", "1300102", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        APUI("APUI", "1300144", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        ATALAIA_DO_NORTE("ATALAIA DO NORTE", "1300201", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        AUTAZES("AUTAZES", "1300300", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        BARCELOS("BARCELOS", "1300409", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        BARREIRINHA("BARREIRINHA", "1300508", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        BENJAMIN_CONSTANT("BENJAMIN CONSTANT", "1300607", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        BERURI("BERURI", "1300631", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        BOA_VISTA_DO_RAMOS("BOA VISTA DO RAMOS", "1300680", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        BOCA_DO_ACRE("BOCA DO ACRE", "1300706", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        BORBA("BORBA", "1300805", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        CAAPIRANGA("CAAPIRANGA", "1300839", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        CANUTAMA("CANUTAMA", "1300904", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        CARAUARI("CARAUARI", "1301001", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        CAREIRO("CAREIRO", "1301100", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        CAREIRO_DA_VARZEA("CAREIRO DA VARZEA", "1301159", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        COARI("COARI", "1301209", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        CODAJAS("CODAJAS", "1301308", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        EIRUNEPE("EIRUNEPE", "1301407", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        ENVIRA("ENVIRA", "1301506", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        FONTE_BOA("FONTE BOA", "1301605", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        GUAJARA("GUAJARA", "1301654", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        HUMAITA("HUMAITA", "1301704", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        IPIXUNA("IPIXUNA", "1301803", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        IRANDUBA("IRANDUBA", "1301852", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        ITACOATIARA("ITACOATIARA", "1301902", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        ITAMARATI("ITAMARATI", "1301951", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        ITAPIRANGA("ITAPIRANGA", "1302009", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        JAPURA("JAPURA", "1302108", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        JURUA("JURUA", "1302207", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        JUTAI("JUTAI", "1302306", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        LABREA("LABREA", "1302405", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        MANACAPURU("MANACAPURU", "1302504", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        MANAQUIRI("MANAQUIRI", "1302553", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        MANAUS("MANAUS", "1302603", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        MANICORE("MANICORE", "1302702", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        MARAA("MARAA", "1302801", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        MAUES("MAUES", "1302900", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        NHAMUNDA("NHAMUNDA", "1303007", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        NOVA_OLINDA_DO_NORTE("NOVA OLINDA DO NORTE", "1303106", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        NOVO_AIRAO("NOVO AIRAO", "1303205", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        NOVO_ARIPUANA("NOVO ARIPUANA", "1303304", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        PARINTINS("PARINTINS", "1303403", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        PAUINI("PAUINI", "1303502", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        PRESIDENTE_FIGUEIREDO("PRESIDENTE FIGUEIREDO", "1303536", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        RIO_PRETO_DA_EVA("RIO PRETO DA EVA", "1303569", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        SANTA_ISABEL_DO_RIO_NEGRO("SANTA ISABEL DO RIO NEGRO", "1303601", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        SANTO_ANTONIO_DO_ICA("SANTO ANTONIO DO ICA", "1303700", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        SILVES("SILVES", "1304005", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        SAO_GABRIEL_DA_CACHOEIRA("SAO GABRIEL DA CACHOEIRA", "1303809", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        SAO_PAULO_DE_OLIVENCA("SAO PAULO DE OLIVENCA", "1303908", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        SAO_SEBASTIAO_DO_UATUMA("SAO SEBASTIAO DO UATUMA", "1303957", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        TABATINGA("TABATINGA", "1304062", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        TAPAUA("TAPAUA", "1304104", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        TEFE("TEFE", "1304203", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        TONANTINS("TONANTINS", "1304237", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        UARINI("UARINI", "1304260", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        URUCARA("URUCARA", "1304302", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name()),
        URUCURITUBA("URUCURITUBA", "1304401", BRASIL.getCode(), AMAZONAS.getCode(), NORTE.name());

        private String description;
        private String code;
        private String country;
        private String state;
        private String region;
    }

    @Getter
    @AllArgsConstructor
    public enum RORAIMA {
        ALTO_ALEGRE("ALTO ALEGRE", "1400050", BRASIL.getCode(), RORAIMA.getCode(), NORTE.name()),
        AMAJARI("AMAJARI", "1400027", BRASIL.getCode(), RORAIMA.getCode(), NORTE.name()),
        BOA_VISTA("BOA VISTA", "1400100", BRASIL.getCode(), RORAIMA.getCode(), NORTE.name()),
        BONFIM("BONFIM", "1400159", BRASIL.getCode(), RORAIMA.getCode(), NORTE.name()),
        CANTA("CANTA", "1400175", BRASIL.getCode(), RORAIMA.getCode(), NORTE.name()),
        CARACARAI("CARACARAI", "1400209", BRASIL.getCode(), RORAIMA.getCode(), NORTE.name()),
        CAROEBE("CAROEBE", "1400233", BRASIL.getCode(), RORAIMA.getCode(), NORTE.name()),
        IRACEMA("IRACEMA", "1400282", BRASIL.getCode(), RORAIMA.getCode(), NORTE.name()),
        MUCAJAI("MUCAJAI", "1400308", BRASIL.getCode(), RORAIMA.getCode(), NORTE.name()),
        NORMANDIA("NORMANDIA", "1400407", BRASIL.getCode(), RORAIMA.getCode(), NORTE.name()),
        PACARAIMA("PACARAIMA", "1400456", BRASIL.getCode(), RORAIMA.getCode(), NORTE.name()),
        RORAINOPOLIS("RORAINOPOLIS", "1400472", BRASIL.getCode(), RORAIMA.getCode(), NORTE.name()),
        SAO_JOAO_DA_BALIZA("SAO JOAO DA BALIZA", "1400506", BRASIL.getCode(), RORAIMA.getCode(), NORTE.name()),
        SAO_LUIZ("SAO LUIZ", "1400605", BRASIL.getCode(), RORAIMA.getCode(), NORTE.name()),
        UIRAMUTA("UIRAMUTA", "1400704", BRASIL.getCode(), RORAIMA.getCode(), NORTE.name());

        private String description;
        private String code;
        private String country;
        private String state;
        private String region;
    }

    @Getter
    @AllArgsConstructor
    public enum PARA {
        ABAETETUBA("ABAETETUBA", "1500107", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        ABEL_FIGUEIREDO("ABEL FIGUEIREDO", "1500131", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        ACARA("ACARA", "1500206", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        AFUA("AFUA", "1500305", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        ALENQUER("ALENQUER", "1500404", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        ALMEIRIM("ALMEIRIM", "1500503", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        ALTAMIRA("ALTAMIRA", "1500602", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        ANAJAS("ANAJAS", "1500701", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        ANANINDEUA("ANANINDEUA", "1500800", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        ANAPU("ANAPU", "1500859", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        AUGUSTO_CORREA("AUGUSTO CORREA", "1500909", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        AURORA_DO_PARA("AURORA DO PARA", "1500958", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        AVEIRO("AVEIRO", "1501006", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        BAGRE("BAGRE", "1501105", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        BAIAO("BAIAO", "1501204", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        BANNACH("BANNACH", "1501253", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        BARCARENA("BARCARENA", "1501303", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        BELTERRA("BELTERRA", "1501451", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        BELEM("BELEM", "1501402", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        BENEVIDES("BENEVIDES", "1501501", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        BOM_JESUS_DO_TOCANTINS("BOM JESUS DO TOCANTINS", "1501576", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        BONITO("BONITO", "1501600", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        BRAGANCA("BRAGANCA", "1501709", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        BRASIL_NOVO("BRASIL NOVO", "1501725", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        BREJO_GRANDE_DO_ARAGUAIA("BREJO GRANDE DO ARAGUAIA", "1501758", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        BREU_BRANCO("BREU BRANCO", "1501782", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        BREVES("BREVES", "1501808", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        BUJARU("BUJARU", "1501907", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        CACHOEIRA_DO_ARARI("CACHOEIRA DO ARARI", "1502004", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        CACHOEIRA_DO_PIRIA("CACHOEIRA DO PIRIA", "1501956", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        CAMETA("CAMETA", "1502103", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        CANAA_DOS_CARAJAS("CANAA DOS CARAJAS", "1502152", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        CAPANEMA("CAPANEMA", "1502202", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        CAPITAO_POCO("CAPITAO POCO", "1502301", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        CASTANHAL("CASTANHAL", "1502400", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        CHAVES("CHAVES", "1502509", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        COLARES("COLARES", "1502608", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        CONCEICAO_DO_ARAGUAIA("CONCEICAO DO ARAGUAIA", "1502707", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        CONCORDIA_DO_PARA("CONCORDIA DO PARA", "1502756", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        CUMARU_DO_NORTE("CUMARU DO NORTE", "1502764", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        CURIONOPOLIS("CURIONOPOLIS", "1502772", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        CURRALINHO("CURRALINHO", "1502806", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        CURUA("CURUA", "1502855", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        CURUCA("CURUCA", "1502905", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        DOM_ELISEU("DOM ELISEU", "1502939", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        ELDORADO_DO_CARAJAS("ELDORADO DO CARAJAS", "1502954", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        FARO("FARO", "1503002", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        FLORESTA_DO_ARAGUAIA("FLORESTA DO ARAGUAIA", "1503044", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        GARRAFAO_DO_NORTE("GARRAFAO DO NORTE", "1503077", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        GOIANESIA_DO_PARA("GOIANESIA DO PARA", "1503093", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        GURUPA("GURUPA", "1503101", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        IGARAPE_ACU("IGARAPE-ACU", "1503200", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        IGARAPE_MIRI("IGARAPE-MIRI", "1503309", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        INHANGAPI("INHANGAPI", "1503408", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        IPIXUNA_DO_PARA("IPIXUNA DO PARA", "1503457", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        IRITUIA("IRITUIA", "1503507", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        ITAITUBA("ITAITUBA", "1503606", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        ITUPIRANGA("ITUPIRANGA", "1503705", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        JACAREACANGA("JACAREACANGA", "1503754", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        JACUNDA("JACUNDA", "1503804", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        JURUTI("JURUTI", "1503903", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        LIMOEIRO_DO_AJURU("LIMOEIRO DO AJURU", "1504000", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        MAGALHAES_BARATA("MAGALHAES BARATA", "1504109", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        MARABA("MARABA", "1504208", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        MARACANA("MARACANA", "1504307", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        MARAPANIM("MARAPANIM", "1504406", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        MARITUBA("MARITUBA", "1504422", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        MEDICILANDIA("MEDICILANDIA", "1504455", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        MELGACO("MELGACO", "1504505", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        MOCAJUBA("MOCAJUBA", "1504604", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        MOJU("MOJU", "1504703", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        MOJUI_DOS_CAMPOS("MOJUI DOS CAMPOS", "1504752", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        MONTE_ALEGRE("MONTE ALEGRE", "1504802", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        MUANA("MUANA", "1504901", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        MAE_DO_RIO("MAE DO RIO", "1504059", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        NOVA_ESPERANCA_DO_PIRIA("NOVA ESPERANCA DO PIRIA", "1504950", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        NOVA_IPIXUNA("NOVA IPIXUNA", "1504976", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        NOVA_TIMBOTEUA("NOVA TIMBOTEUA", "1505007", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        NOVO_PROGRESSO("NOVO PROGRESSO", "1505031", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        NOVO_REPARTIMENTO("NOVO REPARTIMENTO", "1505064", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        OEIRAS_DO_PARA("OEIRAS DO PARA", "1505205", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        ORIXIMINA("ORIXIMINA", "1505304", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        OURILANDIA_DO_NORTE("OURILANDIA DO NORTE", "1505437", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        OUREM("OUREM", "1505403", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        PACAJA("PACAJA", "1505486", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        PALESTINA_DO_PARA("PALESTINA DO PARA", "1505494", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        PARAGOMINAS("PARAGOMINAS", "1505502", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        PARAUAPEBAS("PARAUAPEBAS", "1505536", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        PAU_DARC("PAU D\'ARC", "1505551", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        PEIXE_BOI("PEIXE-BOI", "1505601", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        PICARRA("PICARRA", "1505635", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        PLACAS("PLACAS", "1505650", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        PONTA_DE_PEDRAS("PONTA DE PEDRAS", "1505700", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        PORTEL("PORTEL", "1505809", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        PORTO_DE_MOZ("PORTO DE MOZ", "1505908", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        PRAINHA("PRAINHA", "1506005", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        PRIMAVERA("PRIMAVERA", "1506104", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        QUATIPURU("QUATIPURU", "1506112", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        REDENCAO("REDENCAO", "1506138", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        RIO_MARIA("RIO MARIA", "1506161", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        RONDON_DO_PARA("RONDON DO PARA", "1506187", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        RUROPOLIS("RUROPOLIS", "1506195", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SALINOPOLIS("SALINOPOLIS", "1506203", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SALVATERRA("SALVATERRA", "1506302", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SANTA_BARBARA_DO_PARA("SANTA BARBARA DO PARA", "1506351", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SANTA_CRUZ_DO_ARARI("SANTA CRUZ DO ARARI", "1506401", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SANTA_IZABEL_DO_PARA("SANTA IZABEL DO PARA", "1506500", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SANTA_LUZIA_DO_PARA("SANTA LUZIA DO PARA", "1506559", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SANTA_MARIA_DAS_BARREIRAS("SANTA MARIA DAS BARREIRAS", "1506583", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SANTA_MARIA_DO_PARA("SANTA MARIA DO PARA", "1506609", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SANTANA_DO_ARAGUAIA("SANTANA DO ARAGUAIA", "1506708", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SANTAREM("SANTAREM", "1506807", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SANTAREM_NOVO("SANTAREM NOVO", "1506906", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SANTO_ANTONIO_DO_TAUA("SANTO ANTONIO DO TAUA", "1507003", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SAPUCAIA("SAPUCAIA", "1507755", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SENADOR_JOSE_PORFIRIO("SENADOR JOSE PORFIRIO", "1507805", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SOURE("SOURE", "1507904", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SAO_CAETANO_DE_ODIVELAS("SAO CAETANO DE ODIVELAS", "1507102", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SAO_DOMINGOS_DO_ARAGUAIA("SAO DOMINGOS DO ARAGUAIA", "1507151", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SAO_DOMINGOS_DO_CAPIM("SAO DOMINGOS DO CAPIM", "1507201", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SAO_FRANCISCO_DO_PARA("SAO FRANCISCO DO PARA", "1507409", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SAO_FELIX_DO_XINGU("SAO FELIX DO XINGU", "1507300", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SAO_GERALDO_DO_ARAGUAIA("SAO GERALDO DO ARAGUAIA", "1507458", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SAO_JOAO_DA_PONTA("SAO JOAO DA PONTA", "1507466", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SAO_JOAO_DE_PIRABAS("SAO JOAO DE PIRABAS", "1507474", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SAO_JOAO_DO_ARAGUAIA("SAO JOAO DO ARAGUAIA", "1507508", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SAO_MIGUEL_DO_GUAMA("SAO MIGUEL DO GUAMA", "1507607", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        SAO_SEBASTIAO_DA_BOA_VISTA("SAO SEBASTIAO DA BOA VISTA", "1507706", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        TAILANDIA("TAILANDIA", "1507953", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        TERRA_ALTA("TERRA ALTA", "1507961", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        TERRA_SANTA("TERRA SANTA", "1507979", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        TOME_ACU("TOME-ACU", "1508001", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        TRACUATEUA("TRACUATEUA", "1508035", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        TRAIRAO("TRAIRAO", "1508050", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        TUCUMA("TUCUMA", "1508084", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        TUCURUI("TUCURUI", "1508100", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        ULIANOPOLIS("ULIANOPOLIS", "1508126", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        URUARA("URUARA", "1508159", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        VIGIA("VIGIA", "1508209", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        VISEU("VISEU", "1508308", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        VITORIA_DO_XINGU("VITORIA DO XINGU", "1508357", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        XINGUARA("XINGUARA", "1508407", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        AGUA_AZUL_DO_NORTE("AGUA AZUL DO NORTE", "1500347", BRASIL.getCode(), PARA.getCode(), NORTE.name()),
        OBIDOS("OBIDOS", "1505106", BRASIL.getCode(), PARA.getCode(), NORTE.name());

        private String description;
        private String code;
        private String country;
        private String state;
        private String region;
    }

    @Getter
    @AllArgsConstructor
    public enum AMAPA {
        AMAPA("AMAPA", "1600105", BRASIL.getCode(), State.AMAPA.getCode(), NORTE.name()),
        CALCOENE("CALCOENE", "1600204", BRASIL.getCode(), State.AMAPA.getCode(), NORTE.name()),
        CUTIAS("CUTIAS", "1600212", BRASIL.getCode(), State.AMAPA.getCode(), NORTE.name()),
        FERREIRA_GOMES("FERREIRA GOMES", "1600238", BRASIL.getCode(), State.AMAPA.getCode(), NORTE.name()),
        ITAUBAL("ITAUBAL", "1600253", BRASIL.getCode(), State.AMAPA.getCode(), NORTE.name()),
        LARANJAL_DO_JARI("LARANJAL DO JARI", "1600279", BRASIL.getCode(), State.AMAPA.getCode(), NORTE.name()),
        MACAPA("MACAPA", "1600303", BRASIL.getCode(), State.AMAPA.getCode(), NORTE.name()),
        MAZAGAO("MAZAGAO", "1600402", BRASIL.getCode(), State.AMAPA.getCode(), NORTE.name()),
        OIAPOQUE("OIAPOQUE", "1600501", BRASIL.getCode(), State.AMAPA.getCode(), NORTE.name()),
        PEDRA_BRANCA_DO_AMAPARI("PEDRA BRANCA DO AMAPARI", "1600154", BRASIL.getCode(), State.AMAPA.getCode(), NORTE.name()),
        PORTO_GRANDE("PORTO GRANDE", "1600535", BRASIL.getCode(), State.AMAPA.getCode(), NORTE.name()),
        PRACUUBA("PRACUUBA", "1600550", BRASIL.getCode(), State.AMAPA.getCode(), NORTE.name()),
        SANTANA("SANTANA", "1600600", BRASIL.getCode(), State.AMAPA.getCode(), NORTE.name()),
        SERRA_DO_NAVIO("SERRA DO NAVIO", "1600055", BRASIL.getCode(), State.AMAPA.getCode(), NORTE.name()),
        TARTARUGALZINHO("TARTARUGALZINHO", "1600709", BRASIL.getCode(), State.AMAPA.getCode(), NORTE.name()),
        VITORIA_DO_JARI("VITORIA DO JARI", "1600808", BRASIL.getCode(), State.AMAPA.getCode(), NORTE.name());

        private String description;
        private String code;
        private String country;
        private String state;
        private String region;
    }

    @Getter
    @AllArgsConstructor
    public enum TOCANTINS {
        ABREULANDIA("ABREULANDIA", "1700251", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        AGUIARNOPOLIS("AGUIARNOPOLIS", "1700301", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        ALIANCA_DO_TOCANTINS("ALIANCA DO TOCANTINS", "1700350", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        ALMAS("ALMAS", "1700400", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        ALVORADA("ALVORADA", "1700707", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        ANANAS("ANANAS", "1701002", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        ANGICO("ANGICO", "1701051", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        APARECIDA_DO_RIO_NEGRO("APARECIDA DO RIO NEGRO", "1701101", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        ARAGOMINAS("ARAGOMINAS", "1701309", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        ARAGUACEMA("ARAGUACEMA", "1701903", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        ARAGUANA("ARAGUANA", "1702158", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        ARAGUATINS("ARAGUATINS", "1702208", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        ARAGUACU("ARAGUACU", "1702000", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        ARAGUAINA("ARAGUAINA", "1702109", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        ARAPOEMA("ARAPOEMA", "1702307", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        ARRAIAS("ARRAIAS", "1702406", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        AUGUSTINOPOLIS("AUGUSTINOPOLIS", "1702554", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        AURORA_DO_TOCANTINS("AURORA DO TOCANTINS", "1702703", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        AXIXA_DO_TOCANTINS("AXIXA DO TOCANTINS", "1702901", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        BABACULANDIA("BABACULANDIA", "1703008", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        BANDEIRANTES_DO_TOCANTINS("BANDEIRANTES DO TOCANTINS", "1703057", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        BARRA_DO_OURO("BARRA DO OURO", "1703073", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        BARROLANDIA("BARROLANDIA", "1703107", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        BERNARDO_SAYAO("BERNARDO SAYAO", "1703206", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        BOM_JESUS_DO_TOCANTINS("BOM JESUS DO TOCANTINS", "1703305", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        BRASILANDIA_DO_TOCANTINS("BRASILANDIA DO TOCANTINS", "1703602", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        BREJINHO_DE_NAZARE("BREJINHO DE NAZARE", "1703701", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        BURITI_DO_TOCANTINS("BURITI DO TOCANTINS", "1703800", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        CACHOEIRINHA("CACHOEIRINHA", "1703826", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        CAMPOS_LINDOS("CAMPOS LINDOS", "1703842", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        CARIRI_DO_TOCANTINS("CARIRI DO TOCANTINS", "1703867", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        CARMOLANDIA("CARMOLANDIA", "1703883", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        CARRASCO_BONITO("CARRASCO BONITO", "1703891", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        CASEARA("CASEARA", "1703909", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        CENTENARIO("CENTENARIO", "1704105", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        CHAPADA_DA_NATIVIDADE("CHAPADA DA NATIVIDADE", "1705102", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        CHAPADA_DE_AREIA("CHAPADA DE AREIA", "1704600", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        COLINAS_DO_TOCANTINS("COLINAS DO TOCANTINS", "1705508", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        COLMEIA("COLMEIA", "1716703", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        COMBINADO("COMBINADO", "1705557", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        CONCEICAO_DO_TOCANTINS("CONCEICAO DO TOCANTINS", "1705607", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        COUTO_MAGALHAES("COUTO MAGALHAES", "1706001", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        CRISTALANDIA("CRISTALANDIA", "1706100", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        CRIXAS_DO_TOCANTINS("CRIXAS DO TOCANTINS", "1706258", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        DARCINOPOLIS("DARCINOPOLIS", "1706506", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        DIANOPOLIS("DIANOPOLIS", "1707009", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        DIVINOPOLIS_DO_TOCANTINS("DIVINOPOLIS DO TOCANTINS", "1707108", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        DOIS_IRMAOS_DO_TOCANTINS("DOIS IRMAOS DO TOCANTINS", "1707207", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        DUERE("DUERE", "1707306", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        ESPERANTINA("ESPERANTINA", "1707405", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        FIGUEIROPOLIS("FIGUEIROPOLIS", "1707652", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        FILADELFIA("FILADELFIA", "1707702", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        FORMOSO_DO_ARAGUAIA("FORMOSO DO ARAGUAIA", "1708205", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        FORTALEZA_DO_TABOCAO("FORTALEZA DO TABOCAO", "1708254", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        FATIMA("FATIMA", "1707553", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        GOIANORTE("GOIANORTE", "1708304", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        GOIATINS("GOIATINS", "1709005", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        GUARAI("GUARAI", "1709302", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        GURUPI("GURUPI", "1709500", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        IPUEIRAS("IPUEIRAS", "1709807", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        ITACAJA("ITACAJA", "1710508", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        ITAGUATINS("ITAGUATINS", "1710706", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        ITAPIRATINS("ITAPIRATINS", "1710904", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        ITAPORA_DO_TOCANTINS("ITAPORA DO TOCANTINS", "1711100", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        JAU_DO_TOCANTINS("JAU DO TOCANTINS", "1711506", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        JUARINA("JUARINA", "1711803", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        LAGOA_DA_CONFUSAO("LAGOA DA CONFUSAO", "1711902", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        LAGOA_DO_TOCANTINS("LAGOA DO TOCANTINS", "1711951", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        LAJEADO("LAJEADO", "1712009", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        LAVANDEIRA("LAVANDEIRA", "1712157", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        LIZARDA("LIZARDA", "1712405", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        LUZINOPOLIS("LUZINOPOLIS", "1712454", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        MARIANOPOLIS_DO_TOCANTINS("MARIANOPOLIS DO TOCANTINS", "1712504", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        MATEIROS("MATEIROS", "1712702", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        MAURILANDIA_DO_TOCANTINS("MAURILANDIA DO TOCANTINS", "1712801", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        MIRACEMA_DO_TOCANTINS("MIRACEMA DO TOCANTINS", "1713205", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        MIRANORTE("MIRANORTE", "1713304", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        MONTE_SANTO_DO_TOCANTINS("MONTE SANTO DO TOCANTINS", "1713700", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        MONTE_DO_CARMO("MONTE DO CARMO", "1713601", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        MURICILANDIA("MURICILANDIA", "1713957", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        NATIVIDADE("NATIVIDADE", "1714203", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        NAZARE("NAZARE", "1714302", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        NOVA_OLINDA("NOVA OLINDA", "1714880", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        NOVA_ROSALANDIA("NOVA ROSALANDIA", "1715002", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        NOVO_ACORDO("NOVO ACORDO", "1715101", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        NOVO_ALEGRE("NOVO ALEGRE", "1715150", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        NOVO_JARDIM("NOVO JARDIM", "1715259", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        OLIVEIRA_DE_FATIMA("OLIVEIRA DE FATIMA", "1715507", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        PALMAS("PALMAS", "1721000", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        PALMEIRANTE("PALMEIRANTE", "1715705", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        PALMEIRAS_DO_TOCANTINS("PALMEIRAS DO TOCANTINS", "1713809", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        PALMEIROPOLIS("PALMEIROPOLIS", "1715754", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        PARANA("PARANA", "1716208", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        PARAISO_DO_TOCANTINS("PARAISO DO TOCANTINS", "1716109", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        PAU_DARC("PAU D\'ARC", "1716307", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        PEDRO_AFONSO("PEDRO AFONSO", "1716505", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        PEIXE("PEIXE", "1716604", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        PEQUIZEIRO("PEQUIZEIRO", "1716653", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        PINDORAMA_DO_TOCANTINS("PINDORAMA DO TOCANTINS", "1717008", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        PIRAQUE("PIRAQUE", "1717206", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        PIUM("PIUM", "1717503", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        PONTE_ALTA_DO_BOM_JESUS("PONTE ALTA DO BOM JESUS", "1717800", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        PONTE_ALTA_DO_TOCANTINS("PONTE ALTA DO TOCANTINS", "1717909", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        PORTO_ALEGRE_DO_TOCANTINS("PORTO ALEGRE DO TOCANTINS", "1718006", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        PORTO_NACIONAL("PORTO NACIONAL", "1718204", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        PRAIA_NORTE("PRAIA NORTE", "1718303", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        PRESIDENTE_KENNEDY("PRESIDENTE KENNEDY", "1718402", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        PUGMIL("PUGMIL", "1718451", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        RECURSOLANDIA("RECURSOLANDIA", "1718501", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        RIACHINHO("RIACHINHO", "1718550", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        RIO_SONO("RIO SONO", "1718758", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        RIO_DA_CONCEICAO("RIO DA CONCEICAO", "1718659", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        RIO_DOS_BOIS("RIO DOS BOIS", "1718709", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        SAMPAIO("SAMPAIO", "1718808", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        SANDOLANDIA("SANDOLANDIA", "1718840", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        SANTA_FE_DO_ARAGUAIA("SANTA FE DO ARAGUAIA", "1718865", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        SANTA_MARIA_DO_TOCANTINS("SANTA MARIA DO TOCANTINS", "1718881", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        SANTA_RITA_DO_TOCANTINS("SANTA RITA DO TOCANTINS", "1718899", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        SANTA_ROSA_DO_TOCANTINS("SANTA ROSA DO TOCANTINS", "1718907", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        SANTA_TEREZA_DO_TOCANTINS("SANTA TEREZA DO TOCANTINS", "1719004", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        SANTA_TEREZINHA_DO_TOCANTINS("SANTA TEREZINHA DO TOCANTINS", "1720002", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        SILVANOPOLIS("SILVANOPOLIS", "1720655", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        SUCUPIRA("SUCUPIRA", "1720853", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        SAO_BENTO_DO_TOCANTINS("SAO BENTO DO TOCANTINS", "1720101", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        SAO_FELIX_DO_TOCANTINS("SAO FELIX DO TOCANTINS", "1720150", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        SAO_MIGUEL_DO_TOCANTINS("SAO MIGUEL DO TOCANTINS", "1720200", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        SAO_SALVADOR_DO_TOCANTINS("SAO SALVADOR DO TOCANTINS", "1720259", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        SAO_SEBASTIAO_DO_TOCANTINS("SAO SEBASTIAO DO TOCANTINS", "1720309", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        SAO_VALERIO("SAO VALERIO", "1720499", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        SITIO_NOVO_DO_TOCANTINS("SITIO NOVO DO TOCANTINS", "1720804", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        TAGUATINGA("TAGUATINGA", "1720903", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        TAIPAS_DO_TOCANTINS("TAIPAS DO TOCANTINS", "1720937", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        TALISMA("TALISMA", "1720978", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        TOCANTINOPOLIS("TOCANTINOPOLIS", "1721208", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        TOCANTINIA("TOCANTINIA", "1721109", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        TUPIRAMA("TUPIRAMA", "1721257", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        TUPIRATINS("TUPIRATINS", "1721307", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        WANDERLANDIA("WANDERLANDIA", "1722081", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name()),
        XAMBIOA("XAMBIOA", "1722107", BRASIL.getCode(), TOCANTIS.getCode(), NORTE.name());

        private String description;
        private String code;
        private String country;
        private String state;
        private String region;
    }
}
